### ISSUE TITLE
Fahrradzähldaten im OpenData Portal falsch verlinkt

### ISSUE THREAD

**Issue by silberzwiebel** [od-ms/resources#1]
[Unter diesem Link](https://opendata.stadt-muenster.de/dataset/verkehrsz%C3%A4hlung-fahrradverkehr/resource/b465c089-5548-4541-8e34-2920daa2950e) findet sich nur eine HTML-Seite des Github-Repos, nicht die Zip-Datei.
Danke fürs Fixen :)

**Comment by tomsrocket** [comment]
Danke für den Hinweis! Habe ich geändert.
