### ISSUE TITLE
Es fehlt die Lizenz?

### ISSUE THREAD

**Issue by florath** [od-ms/resources#2]
Ich würde die Daten gerne nutzen. Allerdings ist das nicht möglich, da keine Lizenz angegeben ist. Würden Sie das bitte nachholen?

**Comment by od-ms** [comment]
Hallo, danke für den Hinweis, ich habe die README Datei erweitert, so dass die Links zu den Lizenzen für alle Dateien genannt werden.

**Comment by florath** [comment]
Danke für den Hinweis.
Leider hilft das für die Corona-Zahlen nicht wirklich:

Auf der Web-Seite:
Lizenz	License Not Specified

;-)

**Comment by od-ms** [comment]
Hallo, stimmt, die hatte ich für die Corona-Datei tatsächlich vergessen. Habe die Lizenz nun hinzugefügt, das ist: Datenlizenz Deutschland Namensnennung 2.0. Wird bald auch auf dem Datenportal so angezeigt.
Ein weiterer Hinweis: Ich habe eben noch das Trennzeichen der Korona-Datei auf "," Komma geändert! Dabei soll es aber nun bleiben.

**Comment by florath** [comment]
Super! Vielen Dank.
Als Hinweis: ich würde die Daten in den nächsten Tagen als eine Datenquelle in unser Projekt aufnehmen, welches aus dem #WirVsVirusHackathon hervorgegangen ist.
Es ist sehr schwer verlässliche und nutzbare (Format und Lizenz) Daten zu finden.
https://github.com/florath/wvv-covid19-datapool
